### ISSUE TITLE
tooling idea: a makefile?

### ISSUE THREAD

**Issue by SKalt** [the-mikedavis/tree-sitter-git-commit#10]
I've got a simple makefile for my local tree-sitter workflow to regenerate parser.c based on grammar.js, etc. Mind if I check it in?  I've found running `make` speeds up my local build/test workflow.

**Comment by the-mikedavis** [comment]
I don't want to add redundant build systems: everything generation and testing-wise can already be done with the `tree-sitter` binary and npm covers the local installation of that binary as well as a few scripts for formatting/testing/etc
