### ISSUE TITLE
Broken highlights in helix if branch name has a slash `/` 

### ISSUE THREAD

**Issue by zummenix** [the-mikedavis/tree-sitter-git-commit#12]
<img width="350" alt="Screenshot 2023-08-03 at 00 06 45" src="https://github.com/the-mikedavis/tree-sitter-git-commit/assets/3009258/34087576-0817-488b-a541-24c9042236ff" />

After removing `/` the highlights are restored:
<img width="350" alt="Screenshot 2023-08-03 at 00 07 03" src="https://github.com/the-mikedavis/tree-sitter-git-commit/assets/3009258/f0b3e0d2-2f16-45b9-9aaf-50a5bb168acb" />

I noticed this a couple of days ago. Seemed to have worked before. I have `$HELIX_RUNTIME` set to the local helix repo and I build helix from source.

**Comment by the-mikedavis** [comment]
Fixed in https://github.com/the-mikedavis/tree-sitter-git-commit/commit/4f8fd9b2fb23fb152e3c1ccf9008a64db6032533

**Comment by zummenix** [comment]
Thank you!
