### ISSUE TITLE
feature request: Highlight diff when using `git commit -v`

### ISSUE THREAD

**Issue by rmburg** [the-mikedavis/tree-sitter-git-commit#15]
When writing a commit message with `git commit -v`, a diff of the staged changes is inserted into the commit message editor.
It would be nice if this had some kind of highlighting, e.g. coloring lines starting with "+" green and those starting with "-" red.

**Comment by the-mikedavis** [comment]
This is actually already possible. Here's the query we use to do it in Helix: https://github.com/helix-editor/helix/blob/a1d7997fe303812edafb23ab08eaa8972e4f4c1d/runtime/queries/git-commit/injections.scm#L1-L4

**Comment by rmburg** [comment]
Nice. I'm using helix, and for me diffs are not highlighted. Any idea what could be causing this?

**Comment by the-mikedavis** [comment]
I'm also using verbose commits with Helix, it should work out of the box:

![diff](https://github.com/the-mikedavis/tree-sitter-git-commit/assets/21230295/f2c2ac25-4755-47ab-9477-35fec66f7f5e)

You can check your log file for any errors about diff and you should have a check mark for "Highlight queries" if you run `hx --health diff`.

Also you should make sure that the theme you're using has scopes for `diff.plus` and `diff.minus` - those are the theme keys we use to highlight added and removed lines

**Comment by rmburg** [comment]
After having some difficulty reproducing this (it only happened on one of my two machines), I finally found out that this was caused by the language being set to something other than English. So, this is basically the same issue as #4, but I would expect the parser to at least be robust enough to recognize diff markers even if it doesn't recognize keywords in the comment before it.
