### ISSUE TITLE
I can't get it to work with Neovim

### ISSUE THREAD

**Issue by marcelmanz** [the-mikedavis/tree-sitter-git-commit#5]
This happens with `diff` files too.

Here and example:
<img width="1274" alt="Screenshot 2023-01-05 at 17 36 08" src="https://user-images.githubusercontent.com/62728887/210832467-32342ec7-b3a2-42de-b272-85085d5c50d6.png">

`checkhealth` returns this for `gitcommit`:
```
nvim-treesitter: require("nvim-treesitter.health").check()

Installation ~
- OK `tree-sitter` found 0.20.7 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v19.3.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: Apple clang version 13.1.6 (clang-1316.0.21.2.5)
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

OS Info:
{
  machine = "arm64",
  release = "21.5.0",
  sysname = "Darwin",
  version = "Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000"
} ~


Parser/Features         H L F I J
  - gitcommit           ✓ . . . ✓
```

**Comment by the-mikedavis** [comment]
What are you using for queries?

I don't use neovim so you may have better luck opening this against the nvim-treesitter repo

**Comment by marcelmanz** [comment]
True, I will add the issue there, thanks!

**Comment by gonzus** [comment]
Hey @marcelarie I have had the same symptom for months on my M1 laptop. Did you ever find a solution, or open an issue in the nvim-treesitter repo, that I could follow?

**Comment by marcelmanz** [comment]
you have more info here https://github.com/nvim-treesitter/nvim-treesitter/issues/1854 :)
