### ISSUE TITLE
feaure request: parse git trailers like `git-interpret-trailers` would

### ISSUE THREAD

**Issue by SKalt** [the-mikedavis/tree-sitter-git-commit#6]
I'd like to contribute parsing of git trailers! Git trailers are "lines that look similar to RFC 822 e-mail headers at the end of the otherwise free-form part of a commit message," according to https://git-scm.com/docs/git-interpret-trailers.  Parsing trailers would improve users' workflows by highlighting trailer keys and values differently, and exposing trailer key-value pairs for programmatic access.   

Looking at the [examples section of the `git-interpret-trailers` page](https://git-scm.com/docs/git-interpret-trailers#_examples), trailers can be configured to use arbitrary keys. To avoid parsing key-value pairs with an unknown delimiter, I'd propose recognizing only the most common trailer delimiters, `/[:=#]/`.

**Comment by the-mikedavis** [comment]
Sounds great!

I agree, let's allow just the most common delimiters 👍
