### ISSUE TITLE
Comments without space after `#` not recognized correctly

### ISSUE THREAD

**Issue by A-Walrus** [the-mikedavis/tree-sitter-git-commit#7]
Lines that start with `#` with no space after are not parsed as comments, but git treats them as such.
![image](https://user-images.githubusercontent.com/58790821/226534880-42c790b6-de69-4e2d-89d8-1fbf09291ac9.png)
(If you look at `git log` the line won't appear)

**Comment by the-mikedavis** [comment]
Ah interesting, looks like it's being parsed as a `message` node. I think the precedence might need to be tuned a little so that this ends up as a `comment` node instead
